enum PLAYER_DATA {
	PLAYER_DATA_EDIT_IDTYPE, // Object, Vehicle, Pickup, Actor, Attached
	PLAYER_DATA_EDIT_ID, // Object ID, Vehicle ID, Pickup ID, Actor ID, Attached ID
	PLAYER_DATA_EDIT_ATTACHOBJECT, // Attach this object to other objects and vehicles
	PLAYER_DATA_EDIT_MOVEOBJECT, // Player Object used for click & drag editing
	PLAYER_DATA_EDIT_INDEX, // Object Material/Texture Index
	PLAYER_DATA_EDIT_COLOR, // Color Index
	PLAYER_DATA_DIALOG, // Dialog ID shown
	PLAYER_DATA_BROWSER, // Browser ID shown
	PlayerText: PLAYER_DATA_KEYSTROKE_TD, // "Press key to open dialog"

	bool: PLAYER_DATA_CAM_TOGGLE,
	bool: PLAYER_DATA_CAM_MOVING,
	Float: PLAYER_DATA_CAM_MULTIPLIER,
	PLAYER_DATA_CAM_OBJECTID,
	PLAYER_DATA_CAM_TIMERID,
	bool: PLAYER_DATA_CAM_SPAWN,
	Float: PLAYER_DATA_CAM_X,
	Float: PLAYER_DATA_CAM_Y,
	Float: PLAYER_DATA_CAM_Z,

	bool: PLAYER_DATA_OFFSET_TOGGLE,
	PLAYER_DATA_OFFSET_MODE,
	PLAYER_DATA_OFFSET_TIMERID,
	Float: PLAYER_DATA_OFFSET_MULTIPLIER,

	bool: PLAYER_DATA_ATTACHED_TOGGLE[MAX_ATTACHED_INDEX],
	PLAYER_DATA_ATTACHED_MODEL[MAX_ATTACHED_INDEX],
	PLAYER_DATA_ATTACHED_BONE[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_X[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_Y[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_Z[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_RX[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_RY[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_RZ[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_SX[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_SY[MAX_ATTACHED_INDEX],
	Float: PLAYER_DATA_ATTACHED_SZ[MAX_ATTACHED_INDEX],
	PLAYER_DATA_ATTACHED_COLOR1[MAX_ATTACHED_INDEX],
	PLAYER_DATA_ATTACHED_COLOR2[MAX_ATTACHED_INDEX]
}

new g_PlayerData[MAX_PLAYERS][PLAYER_DATA];
