// Number of items / page for browser dialog
#define MAX_BROWSER_PAGESIZE \
	20

// Max length of search string for browser dialog
#define MAX_BROWSER_SEARCHLEN \
	20

// Dialog ID's start at this number / offset
#define DIALOG_ID_OFFSET \
	1000

// Invalid ID
#define INVALID_DIALOG_ID \
	-1

// Dialog ID'S
enum {
	DIALOGID_MAIN = DIALOG_ID_OFFSET,
	DIALOGID_OBJECT_MAIN,
	DIALOGID_OBJECT_INDEX,
	DIALOGID_OBJECT_COORD,
	DIALOGID_OBJECT_COMMENT,
	DIALOGID_OBJECT_MATSIZE,
	DIALOGID_OBJECT_TEXT,
	DIALOGID_OBJECT_FONTSIZE,
	DIALOGID_COLOR_ALPHA,
	DIALOGID_VEHICLE_MAIN,
	DIALOGID_VEHICLE_COORD,
	DIALOGID_VEHICLE_COMMENT,
	DIALOGID_PICKUP_MAIN,
	DIALOGID_PICKUP_COORD,
	DIALOGID_PICKUP_COMMENT,
	DIALOGID_ATTACH_INDEXLIST,
	DIALOGID_ATTACH_MAIN,
	DIALOGID_ATTACH_BONE,
	DIALOGID_ATTACH_COORD,
	DIALOGID_ACTOR_MAIN,
	DIALOGID_ACTOR_COORD,
	DIALOGID_ACTOR_COMMENT,
	DIALOGID_ACTOR_ANIM_DELTA,
	DIALOGID_ACTOR_ANIM_TIME,
	DIALOGID_MAP_NEW,
	DIALOGID_MAP_SAVE,
	DIALOGID_MAP_LOAD,
	DIALOGID_BROWSER_ID,
	DIALOGID_BROWSER_PAGE,
	DIALOGID_BROWSER_SEARCH,
	MAX_DIALOGS
}

// Browser ID'S
enum {
	BROWSERID_OBJECT_SELECT,
	BROWSERID_OBJECT_CREATE,
	BROWSERID_OBJECT_TEXTURES,
	BROWSERID_OBJECT_COLORS,
	BROWSERID_OBJECT_FONTS,
	BROWSERID_VEHICLE_SELECT,
	BROWSERID_VEHICLE_CREATE,
	BROWSERID_VEHICLE_COLORS,
	BROWSERID_PICKUP_SELECT,
	BROWSERID_PICKUP_CREATE,
	BROWSERID_ATTACH_MODEL,
	BROWSERID_ATTACH_COLORS,
	BROWSERID_ACTOR_SELECT,
	BROWSERID_ACTOR_CREATE,
	BROWSERID_ACTOR_ANIMS,
	MAX_BROWSERS
}

// Listitems for DIALOGID_MAIN
enum {
	LISTITEM_MAIN_OBJECT_3DSELECT,
	LISTITEM_MAIN_OBJECT_LSELECT,
	LISTITEM_MAIN_OBJECT_CREATE,
	LISTITEM_MAIN_VEHICLE_SELECT,
	LISTITEM_MAIN_VEHICLE_CREATE,
	LISTITEM_MAIN_PICKUP_SELECT,
	LISTITEM_MAIN_PICKUP_CREATE,
	LISTITEM_MAIN_ATTACH_SELECT,
	LISTITEM_MAIN_ACTOR_SELECT,
	LISTITEM_MAIN_ACTOR_CREATE,
	LISTITEM_MAIN_CAM,
	LISTITEM_MAIN_NEW,
	LISTITEM_MAIN_SAVE,
	LISTITEM_MAIN_LOAD,
	MAX_LISTITEMS_MAIN
}

// Listitems for DIALOGID_OBJECT_MAIN
enum {
	LISTITEM_OBJECT_GOTO,
	LISTITEM_OBJECT_GET,
	LISTITEM_OBJECT_COORD,
	LISTITEM_OBJECT_MOVE,
	LISTITEM_OBJECT_ATTACH_SELECT,
	LISTITEM_OBJECT_ATTACH_APPLY,
	LISTITEM_OBJECT_ATTACH_REMOVE,
	LISTITEM_OBJECT_DUPLICATE,
	LISTITEM_OBJECT_RECREATE,
	LISTITEM_OBJECT_REMOVE,
	LISTITEM_OBJECT_COMMENT,
	LISTITEM_OBJECT_INDEX_START,
	LISTITEM_OBJECT_INDEX_END = (LISTITEM_OBJECT_INDEX_START + MAX_OBJECT_INDEX) - 1,
	MAX_LISTITEMS_OBJECT
}

// Listitems for DIALOGID_OBJECT_INDEX
enum {
	LISTITEM_OINDEX_REMOVE,
	LISTITEM_OINDEX_TEXTURE,
	LISTITEM_OINDEX_COLOR,
	LISTITEM_OINDEX_ALPHA,
	LISTITEM_OINDEX_REMOVECOLOR,
	LISTITEM_OINDEX_TEXT,
	LISTITEM_OINDEX_MATERIALSIZE,
	LISTITEM_OINDEX_FONTFACE,
	LISTITEM_OINDEX_FONTSIZE,
	LISTITEM_OINDEX_FONTBOLD,
	LISTITEM_OINDEX_FONTALIGN,
	LISTITEM_OINDEX_FONTCOLOR,
	LISTITEM_OINDEX_FONTALPHA,
	LISTITEM_OINDEX_REMOVEFONTCOLOR,
	LISTITEM_OINDEX_BACKCOLOR,
	LISTITEM_OINDEX_REMOVEBACKCOLOR,
	MAX_LISTITEMS_OINDEX
}

// Listitems for DIALOGID_VEHICLE_MAIN
enum {
	LISTITEM_VEHICLE_GOTO,
	LISTITEM_VEHICLE_GET,
	LISTITEM_VEHICLE_DRIVE,
	LISTITEM_VEHICLE_COORD,
	LISTITEM_VEHICLE_MOVE,
	LISTITEM_VEHICLE_ATTACH,
	LISTITEM_VEHICLE_DUPLICATE,
	LISTITEM_VEHICLE_REMOVE,
	LISTITEM_VEHICLE_COMMENT,
	LISTITEM_VEHICLE_COLOR1,
	LISTITEM_VEHICLE_COLOR2,
	LISTITEM_VEHICLE_MODSHOP,
	LISTITEM_VEHICLE_REMOVEMODS,
	MAX_LISTITEMS_VEHICLE
}

// Listitems for DIALOGID_PICKUP_MAIN
enum {
	LISTITEM_PICKUP_GOTO,
	LISTITEM_PICKUP_GET,
	LISTITEM_PICKUP_COORD,
	LISTITEM_PICKUP_MOVE,
	LISTITEM_PICKUP_REMOVE,
	LISTITEM_PICKUP_DUPLICATE,
	LISTITEM_PICKUP_COMMENT,
	MAX_LISTITEMS_PICKUP
}

// Listitems for DIALOGID_ATTACH_MAIN
enum {
	LISTITEM_ATTACH_MODEL,
	LISTITEM_ATTACH_BONE,
	LISTITEM_ATTACH_COORD,
	LISTITEM_ATTACH_MOVE,
	LISTITEM_ATTACH_COLOR1,
	LISTITEM_ATTACH_ALPHA1,
	LISTITEM_ATTACH_COLOR2,
	LISTITEM_ATTACH_ALPHA2,
	LISTITEM_ATTACH_REMOVE,
	MAX_LISTITEMS_ATTACH
}

// Listitems for DIALOGID_ACTOR_MAIN
enum {
	LISTITEM_ACTOR_GOTO,
	LISTITEM_ACTOR_GET,
	LISTITEM_ACTOR_COORD,
	LISTITEM_ACTOR_MOVE,
	LISTITEM_ACTOR_REMOVE,
	LISTITEM_ACTOR_DUPLICATE,
	LISTITEM_ACTOR_COMMENT,
	LISTITEM_ACTOR_ANIM_INDEX,
	LISTITEM_ACTOR_ANIM_DELTA,
	LISTITEM_ACTOR_ANIM_LOOP,
	LISTITEM_ACTOR_ANIM_LOCKX,
	LISTITEM_ACTOR_ANIM_LOCKY,
	LISTITEM_ACTOR_ANIM_FREEZE,
	LISTITEM_ACTOR_ANIM_TIME,
	LISTITEM_ACTOR_ANIM_UPDATE,
	LISTITEM_ACTOR_ANIM_REMOVE,
	MAX_LISTITEMS_ACTOR
}

// Listitems for DIALOGID_BROWSER_ID
enum {
	LISTITEM_BROWSER_ITEM_START,
	LISTITEM_BROWSER_ITEM_END = (LISTITEM_BROWSER_ITEM_START + MAX_BROWSER_PAGESIZE) - 1,
	LISTITEM_BROWSER_SPACE,
	LISTITEM_BROWSER_PREVPAGE,
	LISTITEM_BROWSER_NEXTPAGE,
	LISTITEM_BROWSER_PAGE,
	LISTITEM_BROWSER_SEARCH,
	LISTITEM_BROWSER_UPDATE,
	MAX_LISTITEMS_BROWSER
}
